# Docker Compose file for configuring and running containers for the MongoTracker.Sample project.
# Includes containers for MongoDB, Mongo Express, and the MongoTracker.Sample application itself.

services:
  
  # Service for the MongoTracker.Sample application
  mongotracker.sample:
    image: mongotracker.sample # Container image name
    build:
      context: . # Build context (current directory)
      dockerfile: MongoTracker.Sample/Dockerfile # Path to Dockerfile for building the image
    depends_on:
      - mongotracker.mongo # Dependency on MongoDB service (waits for MongoDB to start before launching the app)

  # Service for MongoDB
  mongotracker.mongo:
    image: mongo:latest # Using the latest official MongoDB image
    ports:
      - "27017:27017" # Exposing port 27017 for host access to MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # MongoDB admin username
      MONGO_INITDB_ROOT_PASSWORD: example # MongoDB admin password

  # Service for Mongo Express (web interface for MongoDB management)
  mongotracker.mongo-express:
    image: mongo-express:latest # Using the latest official Mongo Express image
    ports:
      - "8081:8081" # Exposing port 8081 for host access to Mongo Express
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongotracker.mongo:27017/admin # Connection URL for MongoDB
      ME_CONFIG_BASICAUTH: "false" # Disables web interface authentication
    depends_on:
      - mongotracker.mongo # Dependency on MongoDB service (waits for MongoDB to start before launching Mongo Express)