using System.Collections;

using Incendia.MongoTracker.Builders;
using Incendia.MongoTracker.Entities.Collections;
using Incendia.MongoTracker.Entities.Nodes;
using Incendia.MongoTracker.Enums;
using Incendia.MongoTracker.Metadata;

using MongoDB.Driver;

namespace Incendia.MongoTracker.Entities.Base;

/// <summary>
/// Base class that tracks changes of an entity’s properties, nested objects, and collections.
/// </summary>
internal abstract class ChangeTrackerBase<T> where T : class
{
  #region Fields

  /// <summary>
  /// Cached description of the tracked properties of the entity type.
  /// </summary>
  private readonly TrackingPlan _plan;

  /// <summary>
  /// Stores the initial state of all tracked properties, in the order of <see cref="TrackingPlan.Properties"/>.
  /// </summary>
  private readonly object?[] _state;

  /// <summary>
  /// Stores the modified values of simple properties (created on the first change).
  /// </summary>
  private Dictionary<string, object?>? _changes;

  /// <summary>
  /// Stores tracked nested objects (single object), created when the node has any.
  /// </summary>
  private Dictionary<string, ChildTracker<T>>? _childObjects;

  /// <summary>
  /// Stores tracked primitive or value-type collections, created when the node has any.
  /// </summary>
  private Dictionary<string, CollectionTrackerBase<T>>? _collections;

  /// <summary>
  /// Entity metadata loaded from configuration.
  /// </summary>
  private readonly EntityBuilder? _entityConfig;

  /// <summary>
  /// The latest observed instance of the tracked object.
  /// </summary>
  private object _entity;

  /// <summary>
  /// Version value generated by the last update definition, pending until the write is accepted.
  /// </summary>
  private object? _newVersion;

  #endregion

  #region Properties

  /// <summary>
  /// Concurrency token property names with their initial values (if configured)
  /// </summary>
  public IReadOnlyList<KeyValuePair<string, object?>> ConcurrencyTokens =>
    (
      _entityConfig?.ConcurrencyTokenNames
        .Select(name => new KeyValuePair<string, object?>(name, GetState(name)))
      ?? []
    )
    .Concat(
      ActiveChildObjects.SelectMany(child =>
        child.Value.ConcurrencyTokens.Select(token =>
          new KeyValuePair<string, object?>(
            Utils.CombineName(child.Key, token.Key)!,
            token.Value)))
    )
    .ToList();

  /// <summary>
  /// Version property name and its initial value (if configured)
  /// </summary>
  public KeyValuePair<string, object?>? Version
  {
    get
    {
      string? name = _entityConfig?.VersionPropertyName;
      if (name != null) return new KeyValuePair<string, object?>(name, GetState(name));

      // Fall back to the first nested version, prefixing it with the path of its child object
      return ActiveChildObjects
        .Select(child => child.Value.Version is { } version
          ? new KeyValuePair<string, object?>(Utils.CombineName(child.Key, version.Key)!, version.Value)
          : (KeyValuePair<string, object?>?)null)
        .FirstOrDefault(v => v != null);
    }
  }

  /// <summary>
  /// Indicates whether this node or any of its nested tracked objects or collections
  /// contain modifications compared to the original captured state.
  /// </summary>
  public bool IsModified => _changes?.Count > 0
    || ActiveChildObjects.Any(v => v.Value.IsModified)
    || ActiveCollections.Any(v => v.Value.IsModified);

  /// <summary>
  /// Tracked nested objects that are not replaced as a whole.
  /// </summary>
  private IEnumerable<KeyValuePair<string, ChildTracker<T>>> ActiveChildObjects =>
    _childObjects?.Where(c => !IsReplaced(c.Key)) ?? [];

  /// <summary>
  /// Tracked collections that are not replaced as a whole.
  /// </summary>
  private IEnumerable<KeyValuePair<string, CollectionTrackerBase<T>>> ActiveCollections =>
    _collections?.Where(c => !IsReplaced(c.Key)) ?? [];

  #endregion

  #region Methods

  /// <summary>
  /// Loads the updated values from entity instance.
  /// </summary>
  /// <param name="updatedEntity">The new version of the entity containing updated property values.</param>
  public void TrackChanges(object updatedEntity)
  {
    // Remember the instance and drop versions generated by a previous (possibly failed) commit
    _entity = updatedEntity;
    _newVersion = null;

    // An instance of another type is read by property names through its own metadata
    TypeMetadata? otherType = updatedEntity.GetType() == _plan.Type ? null : TypeMetadata.Get(updatedEntity.GetType());

    // Compare each tracked property with the updated entity
    for (var index = 0; index < _state.Length; index++)
    {
      PropertyAccessor? property = _plan.Properties[index];

      if (otherType != null)
      {
        property = otherType.Find(property.Name);
        if (property == null) continue;
      }

      // Delegate change detection depending on property type (its tracking mode)
      switch (_plan.Kinds[index])
      {
        case PropertyKind.Version:
        case PropertyKind.Ignored:
        case PropertyKind.Identifier:
          break;

        case PropertyKind.Child:
          TrackChildObject(property.Name, index, property.GetValue(updatedEntity));
          break;

        case PropertyKind.Set:
        case PropertyKind.Collection:
        case PropertyKind.TrackedSet:
          TrackCollection(property.Name, index, property.GetValue(updatedEntity));
          break;

        default:
          TrackProperty(property.Name, index, property.GetValue(updatedEntity));
          break;
      }
    }
  }

  /// <summary>
  /// Returns the initial value of a tracked property.
  /// </summary>
  /// <param name="name">The name of the property.</param>
  /// <returns>The value captured when tracking started.</returns>
  /// <exception cref="KeyNotFoundException">Thrown when the property is not tracked.</exception>
  private object? GetState(string name)
  {
    int index = _plan.IndexOf(name);
    if (index < 0) throw new KeyNotFoundException($"Property '{name}' is not tracked.");
    return _state[index];
  }

  /// <summary>
  /// Records a changed value of a property.
  /// </summary>
  /// <param name="name">The name of the property.</param>
  /// <param name="value">The new value.</param>
  private void SetChange(string name, object? value) => (_changes ??= new Dictionary<string, object?>())[name] = value;

  /// <summary>
  /// Forgets a recorded change of a property, e.g. when its original value was restored.
  /// </summary>
  /// <param name="name">The name of the property.</param>
  private void RemoveChange(string name) => _changes?.Remove(name);

  /// <summary>
  /// Checks whether a nested object or collection is written as a whole (it was set or removed), so its
  /// own tracker must not contribute updates, versions or concurrency tokens.
  /// </summary>
  /// <param name="name">The name of the property.</param>
  /// <returns><c>true</c> if the property has a recorded whole-value change.</returns>
  private bool IsReplaced(string name) => _changes?.ContainsKey(name) ?? false;

  /// <summary>
  /// Tracks a change in a simple (non-nested) property by comparing the old and new values.
  /// </summary>
  /// <param name="name">The name of the property being evaluated.</param>
  /// <param name="index">The position of the property in the tracking plan.</param>
  /// <param name="value">The new value read from the updated entity.</param>
  private void TrackProperty(string name, int index, object? value)
  {
    // Get original value from state
    object? oldValue = _state[index];

    // No changes if both are null or values are equal (also when the original value was restored)
    if (Equals(oldValue, value))
    {
      RemoveChange(name);
      return;
    }

    // Record change
    SetChange(name, value);
  }

  /// <summary>
  /// Tracks changes in a nested tracked object.
  /// </summary>
  /// <param name="name">The name of the nested object property.</param>
  /// <param name="index">The position of the property in the tracking plan.</param>
  /// <param name="value">The new nested object instance, or null if removed.</param>
  private void TrackChildObject(string name, int index, object? value)
  {
    // Get original nested object reference
    object? old = _state[index];

    // There was no object: a new one is written as a whole, and none means no change
    if (old == null)
    {
      if (value == null) RemoveChange(name);
      else SetChange(name, value);
      return;
    }

    // Object removed → record null, keeping the tracker in case the object is restored
    if (value == null)
    {
      SetChange(name, null);
      return;
    }

    // Existing (or restored) object → delegate inside-object change tracking
    RemoveChange(name);
    _childObjects![name].TrackChanges(value);
  }

  /// <summary>
  /// Tracks changes in a collection of primitive or simple value types.
  /// </summary>
  /// <param name="name">The name of the collection property.</param>
  /// <param name="index">The position of the property in the tracking plan.</param>
  /// <param name="value">The new collection value, or null if removed.</param>
  private void TrackCollection(string name, int index, object? value)
  {
    // Get original collection
    object? old = _state[index];

    // There was no collection: a new one is written as a whole, and none means no change
    if (old == null)
    {
      if (value == null) RemoveChange(name);
      else SetChange(name, value);
      return;
    }

    // Collection removed → record null, keeping the tracker in case the collection is restored
    if (value == null)
    {
      SetChange(name, null);
      return;
    }

    // Collections without an item-level tracker (non-generic ones) are compared as plain values
    if (_collections == null || !_collections.TryGetValue(name, out CollectionTrackerBase<T>? collection))
    {
      TrackProperty(name, index, value);
      return;
    }

    // Existing (or restored) collection → track item-level changes
    RemoveChange(name);
    collection.TrackChanges((IEnumerable)value);
  }

  /// <summary>
  /// Generates a MongoDB <see cref="UpdateDefinition{T}"/> that represents all accumulated changes in this node.
  /// </summary>
  /// <param name="parent">Optional parent path used when the node represents a nested structure.</param>
  /// <param name="name">The local property name of this node within the parent structure.</param>
  /// <param name="context">Shared state of the update being built (array filters).</param>
  /// <returns>
  /// A combined <see cref="UpdateDefinition{T}"/> representing all modifications found in this node.
  /// </returns>
  public UpdateDefinition<T> GetUpdateDefinition(string? parent, string? name, UpdateContext context)
  {
    // Create update builder root and compute full field prefix
    UpdateDefinitionBuilder<T>? updateBuilder = Builders<T>.Update;
    string? fullName = Utils.CombineName(parent, name);

    // Shortcut reference
    UpdateDefinitionBuilder<T>? update = Builders<T>.Update;

    IEnumerable<KeyValuePair<string, object?>> updatesQuery = _changes ?? [];

    if (_entityConfig?.VersionPropertyName != null)
      updatesQuery = updatesQuery.Where(ch => !string.Equals(ch.Key, _entityConfig.VersionPropertyName));

    // Generate $set operations for modified simple properties
    IEnumerable<UpdateDefinition<T>> propertyUpdates = updatesQuery
      .Select(ch => updateBuilder.Set(Utils.CombineName(fullName, ch.Key), ch.Value));

    // Generate updates for modified nested objects
    IEnumerable<UpdateDefinition<T>> childObjectUpdates = ActiveChildObjects
      .Where(v => v.Value.IsModified)
      .Select(v => v.Value.GetUpdateDefinition(fullName, v.Key, context));

    // Generate updates for changed collections
    IEnumerable<UpdateDefinition<T>?> collectionUpdates = ActiveCollections
      .Where(v => v.Value.IsModified)
      .Select(v => v.Value.GetUpdateDefinition(fullName, v.Key, context));

    // Combine all update definitions into a single MongoDB update document
    IEnumerable<UpdateDefinition<T>?> updates = propertyUpdates
      .Union(childObjectUpdates)
      .Union(collectionUpdates);

    // If a version field is configured, set it to the next version value
    if (_entityConfig?.VersionPropertyName != null)
    {
      string versionName = _entityConfig.VersionPropertyName;

      // Compute the fully qualified field name (including nesting)
      string? fieldName = Utils.CombineName(fullName, versionName);

      // Generate the value on the client so it can be written back into the entity after a successful save
      _newVersion = Utils.NextVersion(GetState(versionName), _entityConfig.Properties[versionName].Type);

      // Add the version update to the update pipeline
      updates = updates.Append(updateBuilder.Set(fieldName, _newVersion));
    }

    // Materialize the updates now, so array filters are registered in the context exactly once
    return update.Combine(updates.ToList());
  }

  /// <summary>
  /// Writes version values generated by the last update definition back into the tracked object and its children.
  /// </summary>
  public void AcceptVersions()
  {
    if (_newVersion != null)
    {
      TypeMetadata.Get(_entity.GetType()).Find(_entityConfig!.VersionPropertyName!)!.SetValue(_entity, _newVersion);
      _newVersion = null;
    }

    foreach (KeyValuePair<string, ChildTracker<T>> child in ActiveChildObjects)
      child.Value.AcceptVersions();

    foreach (KeyValuePair<string, CollectionTrackerBase<T>> collection in ActiveCollections)
      collection.Value.AcceptVersions();
  }

  #endregion

  #region Constructors

  /// <summary>
  /// Initializes a new tracked node by capturing the initial state of all its properties.
  /// </summary>
  /// <param name="entity">The entity instance whose properties should be tracked.</param>
  /// <param name="config">The tracking configuration describing how each property should be treated.</param>
  protected ChangeTrackerBase(object entity, IReadOnlyDictionary<Type, EntityBuilder> config)
  {
    // Find configuration for the entity's exact type
    _entityConfig = config.GetValueOrDefault(entity.GetType());
    _entity = entity;

    // Get the properties to track and their modes (resolved once per type and configuration)
    _plan = TrackingPlan.Get(entity.GetType(), _entityConfig);
    _state = new object?[_plan.Properties.Count];

    // Initialize tracking structures for each property
    for (var index = 0; index < _state.Length; index++)
    {
      PropertyAccessor property = _plan.Properties[index];
      PropertyKind? kind = _plan.Kinds[index];

      // Store the initial value in state
      object? value = property.GetValue(entity);
      _state[index] = value;

      // Initialize nested tracked object
      if (kind == PropertyKind.Child && value != null)
        (_childObjects ??= new Dictionary<string, ChildTracker<T>>())[property.Name] = new ChildTracker<T>(value, config);

      // Initialize collection tracked object
      else if (value is IEnumerable enumerable)
      {
        if (property.ElementType is not { } elementType)
          continue;

        CollectionTrackerBase<T>? collection = kind switch
        {
          PropertyKind.Set => new ValueSetTracker<T>(enumerable, elementType),
          PropertyKind.TrackedSet => new ChildSetTracker<T>(enumerable, elementType, config),
          PropertyKind.Collection => new ValueCollectionTracker<T>(enumerable, elementType),
          _ => null
        };

        if (collection == null)
          continue;

        (_collections ??= new Dictionary<string, CollectionTrackerBase<T>>())[property.Name] = collection;
      }
    }
  }

  #endregion
}
